train_dataset: mini-imagenet
train_dataset_args: {split: train}
tval_dataset: mini-imagenet
tval_dataset_args: {split: test}
val_dataset: mini-imagenet
val_dataset_args: {split: val}

model: meta-baseline
model_args: 
    encoder: resnet12
    encoder_args: {
        # step: 4,
        # encode_type: direct,
        # node_type: PLIFNode,
        # act_fun: AtanGrad,
        }
load_encoder: /home/pym/code/homework/neuroscience/few-shot-meta-baseline/save/meta_mini-imagenet-10shot_meta-baseline-resnet12_10/max-va.pth

n_way: 5
n_shot: 1 # 1
n_query: 15
train_batches: 100 # 200
ep_per_batch: 4 # 4

max_epoch: 20
optimizer: sgd
optimizer_args: {lr: 0.001, weight_decay: 5.e-4}

visualize_datasets: True
